### ISSUE TITLE
Move site from Netlify to Azure Static Web Apps

### ISSUE THREAD

**Issue by coliff** [trimble-oss/devguide#132]
Status: In-progress

Preview: https://lively-rock-075179f10.1.azurestaticapps.net/

- [x] #133

**Comment by binitchoudhary** [comment]
how can we migrate web sites netlify to azure web apps. could you share steps how to do that.

**Comment by coliff** [comment]
> how can we migrate web sites Netlify to azure web apps. could you share steps how to do that.

Sure thing. I recently migrated a few other Trimble sites to Azure Static Web Apps and it was relatively straight-forward. I'll document the steps and share them here.
